"""moved from saving text to moving file path

Revision ID: 16398b046271
Revises: 51fff15309f6
Create Date: 2026-03-21 20:02:17.586287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16398b046271'
down_revision: Union[str, Sequence[str], None] = '51fff15309f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('original_doc', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('chats', 'original_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('original_text', sa.VARCHAR(), nullable=False))
    op.drop_column('chats', 'original_doc')
    # ### end Alembic commands ###
