"""fixed fks with chat and chatbranches

Revision ID: 288ceb74b6cc
Revises: 50d92d31720e
Create Date: 2026-03-19 23:53:13.236666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288ceb74b6cc'
down_revision: Union[str, Sequence[str], None] = '50d92d31720e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
