"""changed the processing status in docs

Revision ID: 452d9e44c956
Revises: f17c37cdcf8c
Create Date: 2026-03-17 17:58:39.024326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452d9e44c956'
down_revision: Union[str, Sequence[str], None] = 'f17c37cdcf8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("docs") as batch_op:
        batch_op.alter_column(
            "proccessing_status",
            existing_type=sa.VARCHAR(length=7),
            nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('docs', 'proccessing_status',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    # ### end Alembic commands ###
