"""save stored minio pdf for sharing

Revision ID: d840f567fe22
Revises: 16398b046271
Create Date: 2026-03-21 20:27:15.968486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd840f567fe22'
down_revision: Union[str, Sequence[str], None] = '16398b046271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('shared_doc', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'shared_doc')
    # ### end Alembic commands ###
