"""schema break and indexes

Revision ID: e8ac63bcd449
Revises: b0b3be0ce3c8
Create Date: 2026-04-04 16:55:17.168665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ac63bcd449'
down_revision: Union[str, Sequence[str], None] = 'b0b3be0ce3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chatbranches_chat_id'), 'chatbranches', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chatbranches_created_at'), 'chatbranches', ['created_at'], unique=False)
    op.create_index(op.f('ix_chatbranches_parent_branch_id'), 'chatbranches', ['parent_branch_id'], unique=False)
    op.create_index(op.f('ix_chats_created_at'), 'chats', ['created_at'], unique=False)
    op.create_index(op.f('ix_chats_is_bookmarked'), 'chats', ['is_bookmarked'], unique=False)
    op.create_index(op.f('ix_chats_share_id'), 'chats', ['share_id'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_index(op.f('ix_messagerevisions_created_at'), 'messagerevisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_messagerevisions_edited_by'), 'messagerevisions', ['edited_by'], unique=False)
    op.create_index(op.f('ix_messagerevisions_message_id'), 'messagerevisions', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_branch_id'), 'messages', ['branch_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_summaryvariants_chat_id'), 'summaryvariants', ['chat_id'], unique=False)
    op.create_index(op.f('ix_summaryvariants_created_at'), 'summaryvariants', ['created_at'], unique=False)
    op.create_index(op.f('ix_summaryvariants_variant_type'), 'summaryvariants', ['variant_type'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_summaryvariants_variant_type'), table_name='summaryvariants')
    op.drop_index(op.f('ix_summaryvariants_created_at'), table_name='summaryvariants')
    op.drop_index(op.f('ix_summaryvariants_chat_id'), table_name='summaryvariants')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_branch_id'), table_name='messages')
    op.drop_index(op.f('ix_messagerevisions_message_id'), table_name='messagerevisions')
    op.drop_index(op.f('ix_messagerevisions_edited_by'), table_name='messagerevisions')
    op.drop_index(op.f('ix_messagerevisions_created_at'), table_name='messagerevisions')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_share_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_is_bookmarked'), table_name='chats')
    op.drop_index(op.f('ix_chats_created_at'), table_name='chats')
    op.drop_index(op.f('ix_chatbranches_parent_branch_id'), table_name='chatbranches')
    op.drop_index(op.f('ix_chatbranches_created_at'), table_name='chatbranches')
    op.drop_index(op.f('ix_chatbranches_chat_id'), table_name='chatbranches')
    # ### end Alembic commands ###
