"""removed username

Revision ID: f17c37cdcf8c
Revises: 917efc6f90be
Create Date: 2026-02-21 20:10:31.262173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f17c37cdcf8c"
down_revision: Union[str, Sequence[str], None] = "917efc6f90be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
