[project]
name = "input_api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.11.0",
    "celery>=5.5.3",
    "docx2python>=3.5.0",
    "fastapi>=0.118.3",
    "gtts>=2.5.4",
    "httpx>=0.28.1",
    "langchain>=1.0.3",
    "langchain-classic>=1.0.0",
    "langchain-core>=1.0.0",
    "langchain-huggingface>=1.0.0",
    "langchain-qdrant>=1.1.0",
    "langchain-text-splitters>=0.3.11",
    "minio>=7.2.18",
    "openai-whisper>=20250625",
    "protobuf>=6.33.0",
    "pydantic>=2.12.0",
    "pydub>=0.25.1",
    "pymupdf>=1.26.5",
    "pytesseract>=0.3.13",
    "python-docx>=1.2.0",
    "python-dotenv>=1.1.1",
    "python-magic>=0.4.27",
    "python-multipart>=0.0.20",
    "python-pptx>=1.0.2",
    "qdrant-client>=1.15.1",
    "redis>=6.4.0",
    "sentence-transformers>=5.1.2",
    "sentencepiece>=0.2.1",
    "sqlalchemy>=2.0.44",
    "torch>=2.8.0",
    "transformers>=4.57.1",
    "uvicorn>=0.37.0",
    "yt-dlp>=2025.10.14",
]
