[project]
name = "new-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=4.1.2",
    "celery>=5.5.3",
    "dotenv>=0.9.9",
    "fastapi>=0.121.0",
    "openai-whisper>=20250625",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.11",
    "pydantic[email]>=2.12.3",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.20",
    "redis>=7.0.1",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.38.0",
    "yt-dlp>=2025.10.22",
]
